name: secret_x_app
description: A VPN/network connection app with a sleek UI.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.4.6
  gif: ^2.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
      - assets/splash.gif
      - assets/icon/icon.png
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
  
